// AUTOGENERATED by pkg/hicli/cmdspec/print; do not edit.

import type { BotCommandList } from "./mxtypes.ts"

export type CommandName =
	"meow"
	| "join"
	| "leave"
	| "invite"
	| "kick"
	| "ban"
	| "myroomnick"
	| "myroomavatar"
	| "globalnick"
	| "globalavatar"
	| "roomname"
	| "roomavatar"
	| "redact"
	| "raw"
	| "unencryptedraw"
	| "rawstate"
	| "discardsession"
	| "devtools"
	| "alias add"
	| "alias del"
	| "converttodm"
	| "converttoroom"
	| "powerlevel"
	| "poll"

export default BotCommandList
