name: JS

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    name: Lint JS

    steps:
      - uses: actions/checkout@v7

      - name: Install dependencies
        run: npm ci --include=dev
        working-directory: ./desktop

      - name: Install desktop dependencies
        run: cd ../desktop && npm ci --include=dev

      - name: Run ESLint
        run: npm run lint

      - name: Run ESLint for desktop
        run: cd ../desktop && npm run lint

      - name: Export Go data
        run: ./export-go-data.sh

      - name: Run vitest
        run: npm test
